
import { NextResponse } from 'next/server';
import { adminDb } from '@/lib/firebase-admin';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, subject, message } = body;

    if (!name || !email || !subject || !message) {
      return new NextResponse('Missing required fields', { status: 400 });
    }

    // The document ID will be automatically generated by Firestore.
    const submissionRef = adminDb.collection('submissions').doc();

    await submissionRef.set({
      name,
      email,
      subject,
      message,
      createdAt: new Date().toISOString(),
      to: "hem.dee.technology@gmail.com"
    });

    return NextResponse.json({ message: 'Submission successful' }, { status: 200 });
  } catch (error) {
    console.error('Error in contact form submission:', error);
    return new NextResponse('Internal Server Error', { status: 500 });
  }
}
