
import { NextResponse } from 'next/server';
import { adminDb } from '@/lib/firebase-admin';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, subject, message } = body;

    if (!name || !email || !subject || !message) {
      return new NextResponse('Missing required fields', { status: 400 });
    }

    // The document ID will be automatically generated by Firestore.
    // Saving to the "mail" collection will trigger the Firebase Mailer extension.
    const mailRef = adminDb.collection('mail').doc();

    await mailRef.set({
      to: "hem.dee.technology@gmail.com",
      message: {
        subject: `New Contact Form Submission: ${subject}`,
        html: `
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Subject:</strong> ${subject}</p>
          <p><strong>Message:</strong></p>
          <p>${message}</p>
        `,
      },
    });

    return NextResponse.json({ message: 'Submission successful' }, { status: 200 });
  } catch (error) {
    console.error('Error in contact form submission:', error);
    return new NextResponse('Internal Server Error', { status: 500 });
  }
}
